name: Download FFmpeg
on:  
 push:  
   branches:  
     - main
jobs:  
 download:  
   runs-on: ubuntu-latest
   steps:  
   - name: Download FFmpeg  
     uses: actions/download-artifact@v2  
     with:  
       name: ffmpeg  
       url: https://ffmpeg.org/download.html  
       path: /tmp/ffmpeg  
     if: success() && github.com/hzxYue/mirrorsoft.git
