
name: Download FFmpeg
on:  
 push:  
   branches:  
     - main
jobs:  
 download:  
   runs-on: ubuntu-latest
   steps:  
   - name: 下载文件  
     uses: actions/download-artifact@v2  
     with:  
       name: ffmpeg  
       url: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip  
       path: /tmp/ffmpeg-latest.zip  
     if: success() && github.event_name!= 'pull_request'
   - name: 解压文件  
     run: |  
       curl -sL https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip -o /tmp/ffmpeg.zip  
       unzip /tmp/ffmpeg.zip -d /tmp/ 
